# Generated by Django 4.1.1 on 2022-09-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
